apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: taskpad
  namespace: argocd

spec:
  project: default

  sources:

    - repoURL: https://github.com/nishant-5/gitops.git
      targetRevision: main
      path: charts/taskpad

      helm:
        valueFiles:
          - $values/envs/dev/values.yaml

    - repoURL: https://github.com/nishant-5/gitops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: taskpad-dev