frontend:
  replicaCount: 1
  image:
    repository: nishantch05/taskpad-frontend
    tag: 92895fc
  service:
    port: 80
  env:
    apiUrl: "/api"
backend:
  replicaCount: 1
  image:
    repository: nishantch05/taskpad-backend
    tag: 92895fc
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
mongodb:
  image:
    repository: mongo
    tag: "8.0"
    pullPolicy: IfNotPresent
  service:
    port: 27017
  storage:
    size: 1Gi
  database: taskpad
